# Generated by Django 4.2.7 on 2025-04-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('type', models.CharField(choices=[('Fast Charger', 'Fast Charger'), ('Level 2', 'Level 2'), ('Supercharger', 'Supercharger')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CCS', 'CCS'), ('CHAdeMO', 'CHAdeMO'), ('Type 2', 'Type 2'), ('J1772', 'J1772'), ('Tesla', 'Tesla')], max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Restrooms', 'Restrooms'), ('WiFi', 'WiFi'), ('Coffee Shop', 'Coffee Shop'), ('Dining', 'Dining'), ('Shopping', 'Shopping'), ('Parking', 'Parking'), ('Park', 'Park')], max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='stations.station')),
            ],
        ),
    ]
